### ISSUE TITLE
Существует ли документация по обработкам HMS?

### ISSUE THREAD

**Issue by UksusoFF** [WendyH/HMSEditor_addon#1]
Подскажите есть ли где-то документация как писать обработки?
Кроме того что описано тут и в соседних файлах: https://github.com/WendyH/HMSEditor_addon/blob/master/HMSEditor/Resources/hms_constants.txt

**Comment by WendyH** [comment]
К сожалению, нет.
Писал как-то тему по созданию подкастов, там как раз для начинающих:
https://hms.lostcut.net/viewtopic.php?id=68
Можно примерно разобраться и с написанием обработок, взяв за примеры, какие-нибудь отсюда:
https://hms.lostcut.net/viewforum.php?id=10
С документацией всё печально, отчасти именно поэтому HMSEditor_addon вообще появился. Там хоть подсказки более полные, которые я чисто по опыту от себя добавлял с примерами. Огромный, кстати, труд был.

**Comment by UksusoFF** [comment]
Спасибо за проделанную работу!

> Можно примерно разобраться и с написанием обработок, взяв за примеры, какие-нибудь отсюда

Как раз пытаюсь разобраться и добиться отображения на ТВ обложки и описания с TheMovieDB.
Получилось отобразить описание засунув его вместо mpiTimeLength, но есть подозрение что это кривая дорожка.

Хотелось бы понять что и как отдает HMS, но пока попытки добраться дальше http://x.x.x.x:45397/UPnPServices/ContentDirectory/description.xml не особо успешные.

https://github.com/jellyfin/jellyfin кстати из коробки показывает обложки и описания, так что ТВ это точно поддерживает...

**Comment by UksusoFF** [comment]
P.S. А разработчик HMS на контакт не идет? Очень странно добавить возможность писать плагины и не добавить документации по ним... Кроме HMSEditor_addon вообще еще что-то существует?

**Comment by WendyH** [comment]
) Да, подозреваю, это дорога не прямая.
Разработчик иногда на контакт идёт, но чаще - нет.
Кроме моего, были только примеры дополнений от него:
http://homemediaserver.ru/forum/viewforum.php?f=24
С описанием интерфейсов для разработчиков.

Отображение обложки и инфы планируется где?
DLNA страндарт не очень много даёт возможностей для отображения инфы. Если на медиа-сервер заходить через веб-интерфейс, то там ещё можно отображать всё, что удобно.
Если на телеке, **через DLNA**, то, боюсь, это тупик.
(в отличии от ситуации, когда медиа-сервер также является и медиа-плеером и использует телек только для отображения через hdmi)

Через DLNA телеку можно передать только поля description, title, time. Но я не видел, чтобы телеки отображали описание (только название, дату файла и время). Хотя всё зависит от самого телека, вдруг у кого и отображается.

**Comment by UksusoFF** [comment]
Превьюшки же HMS показывает, значит как-то теоретически можно вместо них вывести и обложки... Банально через "Командная строка для создания эскизов фильмов" можно оттуда что-то другое вернуть. Но хотелось бы по людски...

Вообще у меня много чего показывается - жанр, рейтинг, год, актерский состав: https://yadi.sk/d/_1x8oPsWqhBaFA
